remote_theme: 0xd4y/jekyll-theme-console

header_pages:
  - HackTheBox.markdown
  - TryHackMe.markdown
  - Contact.markdown
  - index.markdown
style: dark
plugins:
  - jekyll-seo-tag
future: true

footer: footer: '<a href="https://github.com/0xd4y/Writeups" class="class7">0xd4y</a><a href="https://github.com/0xd4y/Writeups" class="class5">@</a><a href="https://github.com/0xd4y/Writeups" class="class6">Writeup</a><a href="https://github.com/0xd4y/Writeups"> Github</a>'
