remote_theme: 0xd4y/jekyll-theme-console

header_pages:
  - HackTheBox.markdown
  - TryHackMe.markdown
  - ctf.markdown
  - Misc.markdown
  - Notes.markdown
  - Contact.markdown
  - index.markdown
  
  
style: dark
plugins:
  - jekyll-seo-tag
future: true

footer: '<a href="https://raw.githubusercontent.com/0xd4y/Writeups/gh-pages/images/0xd4y-Logo-Black-Small.jpg" class="class7">0xd4y</a><a href="https://raw.githubusercontent.com/0xd4y/Writeups/gh-pages/images/0xd4y-Logo-Black-Small.jpg" class="class5">@</a><a href="https://raw.githubusercontent.com/0xd4y/Writeups/gh-pages/images/0xd4y-Logo-Black-Small.jpg" class="class6">Writeup</a>'
