remote_theme: 0xd4y/jekyll-theme-console

header_pages:
  - HackTheBox.markdown
  - TryHackMe.markdown
  - Contact.markdown
  - index.markdown
style: dark
plugins:
  - jekyll-seo-tag
future: true
listen_for_clients_preferred_style: true
